// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/account/v1/account.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerType int32

const (
	TriggerType_TRIGGER_UNKNOWN   TriggerType = 0 // 未知触发方式（默认值）
	TriggerType_TRIGGER_MANUAL    TriggerType = 1 // 手动触发（如管理员点击按钮）
	TriggerType_TRIGGER_SCHEDULED TriggerType = 2 // 定时任务触发（如每天凌晨2点自动同步）
)

// Enum value maps for TriggerType.
var (
	TriggerType_name = map[int32]string{
		0: "TRIGGER_UNKNOWN",
		1: "TRIGGER_MANUAL",
		2: "TRIGGER_SCHEDULED",
	}
	TriggerType_value = map[string]int32{
		"TRIGGER_UNKNOWN":   0,
		"TRIGGER_MANUAL":    1,
		"TRIGGER_SCHEDULED": 2,
	}
)

func (x TriggerType) Enum() *TriggerType {
	p := new(TriggerType)
	*p = x
	return p
}

func (x TriggerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_account_v1_account_proto_enumTypes[0].Descriptor()
}

func (TriggerType) Type() protoreflect.EnumType {
	return &file_api_account_v1_account_proto_enumTypes[0]
}

func (x TriggerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerType.Descriptor instead.
func (TriggerType) EnumDescriptor() ([]byte, []int) {
	return file_api_account_v1_account_proto_rawDescGZIP(), []int{0}
}

type SyncType int32

const (
	SyncType_FULL        SyncType = 0 // 全量同步
	SyncType_INCREMENTAL SyncType = 1 // 增量同步
)

// Enum value maps for SyncType.
var (
	SyncType_name = map[int32]string{
		0: "FULL",
		1: "INCREMENTAL",
	}
	SyncType_value = map[string]int32{
		"FULL":        0,
		"INCREMENTAL": 1,
	}
)

func (x SyncType) Enum() *SyncType {
	p := new(SyncType)
	*p = x
	return p
}

func (x SyncType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_account_v1_account_proto_enumTypes[1].Descriptor()
}

func (SyncType) Type() protoreflect.EnumType {
	return &file_api_account_v1_account_proto_enumTypes[1]
}

func (x SyncType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncType.Descriptor instead.
func (SyncType) EnumDescriptor() ([]byte, []int) {
	return file_api_account_v1_account_proto_rawDescGZIP(), []int{1}
}

type GetSyncAccountReply_Status int32

const (
	GetSyncAccountReply_PENDING GetSyncAccountReply_Status = 0 // 待执行
	GetSyncAccountReply_RUNNING GetSyncAccountReply_Status = 1 // 执行中
	GetSyncAccountReply_SUCCESS GetSyncAccountReply_Status = 2 // 成功
	GetSyncAccountReply_FAILED  GetSyncAccountReply_Status = 3 // 失败
)

// Enum value maps for GetSyncAccountReply_Status.
var (
	GetSyncAccountReply_Status_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "SUCCESS",
		3: "FAILED",
	}
	GetSyncAccountReply_Status_value = map[string]int32{
		"PENDING": 0,
		"RUNNING": 1,
		"SUCCESS": 2,
		"FAILED":  3,
	}
)

func (x GetSyncAccountReply_Status) Enum() *GetSyncAccountReply_Status {
	p := new(GetSyncAccountReply_Status)
	*p = x
	return p
}

func (x GetSyncAccountReply_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetSyncAccountReply_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_account_v1_account_proto_enumTypes[2].Descriptor()
}

func (GetSyncAccountReply_Status) Type() protoreflect.EnumType {
	return &file_api_account_v1_account_proto_enumTypes[2]
}

func (x GetSyncAccountReply_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetSyncAccountReply_Status.Descriptor instead.
func (GetSyncAccountReply_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_account_v1_account_proto_rawDescGZIP(), []int{3, 0}
}

// 创建同步请求
type CreateSyncAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerType   TriggerType            `protobuf:"varint,1,opt,name=trigger_type,json=triggerType,proto3,enum=api.account.v1.TriggerType" json:"trigger_type,omitempty"` // 触发类型
	SyncType      SyncType               `protobuf:"varint,2,opt,name=sync_type,json=syncType,proto3,enum=api.account.v1.SyncType" json:"sync_type,omitempty"`             // 同步类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSyncAccountRequest) Reset() {
	*x = CreateSyncAccountRequest{}
	mi := &file_api_account_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSyncAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSyncAccountRequest) ProtoMessage() {}

func (x *CreateSyncAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSyncAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateSyncAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_account_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSyncAccountRequest) GetTriggerType() TriggerType {
	if x != nil {
		return x.TriggerType
	}
	return TriggerType_TRIGGER_UNKNOWN
}

func (x *CreateSyncAccountRequest) GetSyncType() SyncType {
	if x != nil {
		return x.SyncType
	}
	return SyncType_FULL
}

// 创建同步响应
type CreateSyncAccountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`             // 生成的任务ID
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 任务创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSyncAccountReply) Reset() {
	*x = CreateSyncAccountReply{}
	mi := &file_api_account_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSyncAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSyncAccountReply) ProtoMessage() {}

func (x *CreateSyncAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSyncAccountReply.ProtoReflect.Descriptor instead.
func (*CreateSyncAccountReply) Descriptor() ([]byte, []int) {
	return file_api_account_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSyncAccountReply) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateSyncAccountReply) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// 查询同步请求
type GetSyncAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 要查询的任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncAccountRequest) Reset() {
	*x = GetSyncAccountRequest{}
	mi := &file_api_account_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncAccountRequest) ProtoMessage() {}

func (x *GetSyncAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncAccountRequest.ProtoReflect.Descriptor instead.
func (*GetSyncAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_account_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *GetSyncAccountRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 查询同步响应
type GetSyncAccountReply struct {
	state                       protoimpl.MessageState     `protogen:"open.v1"`
	Status                      GetSyncAccountReply_Status `protobuf:"varint,1,opt,name=status,proto3,enum=api.account.v1.GetSyncAccountReply_Status" json:"status,omitempty"`
	UserCount                   int64                      `protobuf:"varint,2,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	DepartmentCount             int64                      `protobuf:"varint,3,opt,name=department_count,json=departmentCount,proto3" json:"department_count,omitempty"`
	UserDepartmentRelationCount int64                      `protobuf:"varint,4,opt,name=user_department_relation_count,json=userDepartmentRelationCount,proto3" json:"user_department_relation_count,omitempty"`
	LatestSyncTime              *timestamppb.Timestamp     `protobuf:"bytes,5,opt,name=latest_sync_time,json=latestSyncTime,proto3" json:"latest_sync_time,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *GetSyncAccountReply) Reset() {
	*x = GetSyncAccountReply{}
	mi := &file_api_account_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncAccountReply) ProtoMessage() {}

func (x *GetSyncAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncAccountReply.ProtoReflect.Descriptor instead.
func (*GetSyncAccountReply) Descriptor() ([]byte, []int) {
	return file_api_account_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *GetSyncAccountReply) GetStatus() GetSyncAccountReply_Status {
	if x != nil {
		return x.Status
	}
	return GetSyncAccountReply_PENDING
}

func (x *GetSyncAccountReply) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *GetSyncAccountReply) GetDepartmentCount() int64 {
	if x != nil {
		return x.DepartmentCount
	}
	return 0
}

func (x *GetSyncAccountReply) GetUserDepartmentRelationCount() int64 {
	if x != nil {
		return x.UserDepartmentRelationCount
	}
	return 0
}

func (x *GetSyncAccountReply) GetLatestSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LatestSyncTime
	}
	return nil
}

type CancelSyncAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 要删除的任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSyncAccountRequest) Reset() {
	*x = CancelSyncAccountRequest{}
	mi := &file_api_account_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSyncAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSyncAccountRequest) ProtoMessage() {}

func (x *CancelSyncAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSyncAccountRequest.ProtoReflect.Descriptor instead.
func (*CancelSyncAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_account_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *CancelSyncAccountRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_api_account_v1_account_proto protoreflect.FileDescriptor

const file_api_account_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x1capi/account/v1/account.proto\x12\x0eapi.account.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x91\x01\n" +
	"\x18CreateSyncAccountRequest\x12>\n" +
	"\ftrigger_type\x18\x01 \x01(\x0e2\x1b.api.account.v1.TriggerTypeR\vtriggerType\x125\n" +
	"\tsync_type\x18\x02 \x01(\x0e2\x18.api.account.v1.SyncTypeR\bsyncType\"n\n" +
	"\x16CreateSyncAccountReply\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12;\n" +
	"\vcreate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"0\n" +
	"\x15GetSyncAccountRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xeb\x02\n" +
	"\x13GetSyncAccountReply\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.api.account.v1.GetSyncAccountReply.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"user_count\x18\x02 \x01(\x03R\tuserCount\x12)\n" +
	"\x10department_count\x18\x03 \x01(\x03R\x0fdepartmentCount\x12C\n" +
	"\x1euser_department_relation_count\x18\x04 \x01(\x03R\x1buserDepartmentRelationCount\x12D\n" +
	"\x10latest_sync_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0elatestSyncTime\";\n" +
	"\x06Status\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\"3\n" +
	"\x18CancelSyncAccountRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId*M\n" +
	"\vTriggerType\x12\x13\n" +
	"\x0fTRIGGER_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eTRIGGER_MANUAL\x10\x01\x12\x15\n" +
	"\x11TRIGGER_SCHEDULED\x10\x02*%\n" +
	"\bSyncType\x12\b\n" +
	"\x04FULL\x10\x00\x12\x0f\n" +
	"\vINCREMENTAL\x10\x012\xf8\x02\n" +
	"\aAccount\x12}\n" +
	"\x11CreateSyncAccount\x12(.api.account.v1.CreateSyncAccountRequest\x1a&.api.account.v1.CreateSyncAccountReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/account\x12{\n" +
	"\x0eGetSyncAccount\x12%.api.account.v1.GetSyncAccountRequest\x1a#.api.account.v1.GetSyncAccountReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/account/{task_id}\x12q\n" +
	"\x0eCancelSyncTask\x12(.api.account.v1.CancelSyncAccountRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/account/{task_id}B?\n" +
	"\x0eapi.account.v1B\x0eAccountProtoV1P\x01Z\x1bnancalacc/api/account/v1;v1b\x06proto3"

var (
	file_api_account_v1_account_proto_rawDescOnce sync.Once
	file_api_account_v1_account_proto_rawDescData []byte
)

func file_api_account_v1_account_proto_rawDescGZIP() []byte {
	file_api_account_v1_account_proto_rawDescOnce.Do(func() {
		file_api_account_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_account_v1_account_proto_rawDesc), len(file_api_account_v1_account_proto_rawDesc)))
	})
	return file_api_account_v1_account_proto_rawDescData
}

var file_api_account_v1_account_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_account_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_account_v1_account_proto_goTypes = []any{
	(TriggerType)(0),                 // 0: api.account.v1.TriggerType
	(SyncType)(0),                    // 1: api.account.v1.SyncType
	(GetSyncAccountReply_Status)(0),  // 2: api.account.v1.GetSyncAccountReply.Status
	(*CreateSyncAccountRequest)(nil), // 3: api.account.v1.CreateSyncAccountRequest
	(*CreateSyncAccountReply)(nil),   // 4: api.account.v1.CreateSyncAccountReply
	(*GetSyncAccountRequest)(nil),    // 5: api.account.v1.GetSyncAccountRequest
	(*GetSyncAccountReply)(nil),      // 6: api.account.v1.GetSyncAccountReply
	(*CancelSyncAccountRequest)(nil), // 7: api.account.v1.CancelSyncAccountRequest
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 9: google.protobuf.Empty
}
var file_api_account_v1_account_proto_depIdxs = []int32{
	0, // 0: api.account.v1.CreateSyncAccountRequest.trigger_type:type_name -> api.account.v1.TriggerType
	1, // 1: api.account.v1.CreateSyncAccountRequest.sync_type:type_name -> api.account.v1.SyncType
	8, // 2: api.account.v1.CreateSyncAccountReply.create_time:type_name -> google.protobuf.Timestamp
	2, // 3: api.account.v1.GetSyncAccountReply.status:type_name -> api.account.v1.GetSyncAccountReply.Status
	8, // 4: api.account.v1.GetSyncAccountReply.latest_sync_time:type_name -> google.protobuf.Timestamp
	3, // 5: api.account.v1.Account.CreateSyncAccount:input_type -> api.account.v1.CreateSyncAccountRequest
	5, // 6: api.account.v1.Account.GetSyncAccount:input_type -> api.account.v1.GetSyncAccountRequest
	7, // 7: api.account.v1.Account.CancelSyncTask:input_type -> api.account.v1.CancelSyncAccountRequest
	4, // 8: api.account.v1.Account.CreateSyncAccount:output_type -> api.account.v1.CreateSyncAccountReply
	6, // 9: api.account.v1.Account.GetSyncAccount:output_type -> api.account.v1.GetSyncAccountReply
	9, // 10: api.account.v1.Account.CancelSyncTask:output_type -> google.protobuf.Empty
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_account_v1_account_proto_init() }
func file_api_account_v1_account_proto_init() {
	if File_api_account_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_account_v1_account_proto_rawDesc), len(file_api_account_v1_account_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_account_v1_account_proto_goTypes,
		DependencyIndexes: file_api_account_v1_account_proto_depIdxs,
		EnumInfos:         file_api_account_v1_account_proto_enumTypes,
		MessageInfos:      file_api_account_v1_account_proto_msgTypes,
	}.Build()
	File_api_account_v1_account_proto = out.File
	file_api_account_v1_account_proto_goTypes = nil
	file_api_account_v1_account_proto_depIdxs = nil
}
